// src/views/Article/index.tsx
import React, { useState, useEffect } from 'react';
import { Spin, PageHeader, Table, message, Button, Divider, Popconfirm } from 'antd';

import { ReloadOutlined } from '@ant-design/icons';
import Axios, { AxiosResponse } from 'axios';
import { API_STATUS } from '../../constants';
import { RouteChildrenProps } from 'react-router-dom';
import { ColumnsType } from 'antd/lib/table';

const Article = (props: RouteChildrenProps) => {
  const [loading, setLoading] = useState(false);
  const [dataSource, setDataSource] = useState([]);

  // created
  useEffect(() => {
    getData();
  }, []);

  // 分页
  async function getData() {
    setLoading(true);
    const res = (await Axios.get('/article')) as AxiosResponse['data'];
    setLoading(false);

    if (res.status === API_STATUS.SUCCESS) {
      setDataSource(res.result.data);
    } else {
      message.error(res.message);
    }
  }

  function handleAdd() {
    props.history.push('/writing');
  }

  function handleEdit(id: string) {
    props.history.push('/writing?id=' + id);
  }
  async function handleDelete(id: string) {
    const res = (await Axios.delete('/category/' + id)) as AxiosResponse['data'];
    if (res.status === API_STATUS.SUCCESS) {
      message.success(res.message);
    } else {
      message.error(res.message);
    }
  }

  const columns: ColumnsType<any> = [
    {
      title: '标题',
      dataIndex: 'title'
    },
    {
      title: '描述',
      dataIndex: 'description'
    },
    {
      title: '分类',
      align: 'center',

      render: (row: any) => <span>{row.category ? row.category.name : ''}</span>
    },
    {
      title: '操作',
      align: 'center',
      render: (row: any) => [
        <Button type="link" key="1" onClick={_ => handleEdit(row.id)}>
          编辑
        </Button>,
        <Popconfirm key="2" title="确认删除" onConfirm={_ => handleDelete(row.id)} okText="删除" cancelText="取消">
          <Button type="link">转草稿</Button>
        </Popconfirm>
      ]
    }
  ];

  return (
    <Spin spinning={loading}>
      <PageHeader
        title=""
        extra={[
          <Button key="1" type="primary" onClick={handleAdd} style={{ marginRight: '8px' }}>
            新增
          </Button>,
          <Divider type="vertical" key="2" />,
          <ReloadOutlined key="3" style={{ cursor: 'pointer', userSelect: 'none' }} onClick={getData} />
        ]}
      ></PageHeader>
      <Table dataSource={dataSource} columns={columns} rowKey="id"></Table>
    </Spin>
  );
};

export default Article;

// src/views/Article.vue
<template>
  <div id="Article">
    <Card :bordered="false">
      <Table :columns="columns" :data="dataSource"></Table>
      <Page style="margin-top:20px" :total="total" :page-size="pageSize" @on-change="onPageChange" />
    </Card>
  </div>
</template>

<script>
import dayjs from 'dayjs';
import { Button, Tag } from 'view-design';

export default {
  data() {
    return {
      dataSource: [],
      total: 0,
      pageSize: 3,
      page: 1,
      columns: [
        {
          type: 'index',
          align: 'center',
          width: 60
        },
        {
          title: '标题',
          key: 'title'
        },
        {
          title: '描述',
          key: 'description'
        },
        {
          title: '分类',
          align: 'center',

          render: (h, { row }) => {
            return <span>{row.category == null ? '未分类' : <Tag color="default">{row.category.name}</Tag>}</span>;
          }
        },
        {
          title: '标签',
          align: 'center',

          render: (h, { row }) => {
            return <div style="padding:5px 0;">{row.tags ? row.tags.split(',').map((x, i) => <Tag key={i}>{x}</Tag>) : ''}</div>;
          }
        },
        {
          title: '修改时间',
          width: 140,
          align: 'center',
          render: (h, { row }) => {
            return <span>{dayjs(row.updatedAt).format('YYYY-MM-DD')}</span>;
          }
        },
        {
          title: '操作',
          width: 130,
          align: 'center',
          render: (h, { row }) => {
            return (
              <div>
                <Button size="small" type="primary" style="margin-right:5px" on-click={_ => this.handleUpdate(row)}>
                  编辑
                </Button>
                <Button size="small" type="error" on-click={_ => this.handleDelete(row)}>
                  删除
                </Button>
              </div>
            );
          }
        }
      ]
    };
  },
  created() {
    this.getData();
  },
  methods: {
    async getData(index = 1) {
      this.page = index;

      let res = await this.$http(`/article?page=${this.page}&pageSize=${this.pageSize}`);

      this.dataSource = res.result.data;
      this.total = res.result.attribute.count;
    },
    onPageChange(index) {
      this.getData(index);
    },
    handleUpdate(row) {
      this.$router.push(`/writing?id=${row.id}`);
    },
    async handleDelete(row) {
      let res = await this.$http({
        method: 'delete',
        url: `/article/${row.id}`
      });
      if (res.status == 'success') {
        this.$Message.success('删除成功');
        this.getData();
      } else {
        this.$Message.error(res.message);
      }
    }
  }
};
</script>

<style></style>
