// src/views/Category/index.tsx
import React, { useState, useEffect } from 'react';
import Axios, { AxiosResponse } from 'axios';
import { message, Table, Spin, PageHeader, Button, Modal, Input, Divider } from 'antd';
import { ReloadOutlined } from '@ant-design/icons';
import { API_STATUS } from '../../constants';
import dayjs from 'dayjs';
import { ColumnsType } from 'antd/lib/table';

const Category = (props: any) => {
  const [loading, setLoading] = useState(false);
  const [loadingEditBtn, setLoadingEditBtn] = useState(false);
  const [dataSource, setDataSource] = useState([]);

  useEffect(() => {
    getData();
  }, []);

  async function getData() {
    setLoading(true);
    const res = (await Axios.get('/category')) as AxiosResponse['data'];
    setLoading(false);
    if (res.status === API_STATUS.SUCCESS) {
      setDataSource(res.result.data);
    } else {
      message.error(res.message);
    }
  }

  enum editTypes {
    ADD,
    EDIT
  }
  const [showEditModal, setShowEditModal] = useState(false);
  const [editForm, setEditForm] = useState({ name: '' });
  const [editType, setEditType] = useState<editTypes>(editTypes.ADD);
  const [editId, setEditId] = useState<string>('');

  // 新增/编辑
  function handleEdit(type: editTypes, row?: any) {
    console.log(row);
    setEditType(type);
    if (type === editTypes.ADD) {
      setEditForm({ name: '' });
    } else {
      setEditForm({ name: row.name });
      setEditId(row.id);
    }
    setShowEditModal(true);
  }
  // 新增
  async function handleSubmit() {
    const req = {
      name: editForm.name
    };
    const api = editType === editTypes.ADD ? '/category' : `/category/${editId}`;
    const method = editType === editTypes.ADD ? 'post' : 'put';

    setLoadingEditBtn(true);
    let res = (await Axios[method](api, req)) as AxiosResponse['data'];
    setLoadingEditBtn(false);

    if (res.status === API_STATUS.SUCCESS) {
      message.success(res.message);
      setShowEditModal(false);
      getData();
    } else {
      message.error(res.message);
    }
  }

  // 删除
  async function deleteCategory(row: any) {
    if (row.articles.length) {
      return message.error(`该分类有${row.articles.length}篇文章，要删除分类请先删除分类下的文章`);
    }
    setLoading(true);
    const res = (await Axios.delete(`/category/${row.id}`)) as AxiosResponse['data'];
    setLoading(false);
    if (res.status === API_STATUS.SUCCESS) {
      message.success(res.message);
      getData();
    }
  }
  const columns: ColumnsType<any> = [
    {
      title: '分类名称',
      dataIndex: 'name'
    },
    {
      title: '修改时间',
      dataIndex: 'updatedAt',
      render: (updatedAt: string) => <span>{dayjs(updatedAt).format('YYYY-MM-DD')}</span>
    },
    {
      title: '文章数',
      align: 'center',
      dataIndex: 'articles',
      render: (articles: Array<object>) => <span>{articles.length}</span>
    },
    {
      title: '操作',
      align: 'center',
      render: (row: any) => {
        return [
          <Button type="link" key="1" onClick={_ => handleEdit(editTypes.EDIT, row)}>
            编辑
          </Button>,
          <Button type="link" key="2" onClick={_ => deleteCategory(row)}>
            删除
          </Button>
        ];
      }
    }
  ];
  return (
    <Spin spinning={loading}>
      <div className="tablebox">
        <PageHeader
          className="site-page-header"
          title=""
          extra={[
            <Button key="1" type="primary" onClick={_ => handleEdit(editTypes.ADD)} style={{ marginRight: '8px' }}>
              新增
            </Button>,
            <Divider type="vertical" key="2" />,
            <ReloadOutlined key="3" style={{ cursor: 'pointer', userSelect: 'none' }} onClick={getData} />
          ]}
        ></PageHeader>
        <Table dataSource={dataSource} columns={columns} rowKey="id"></Table>
        <Modal
          title={editType === editTypes.ADD ? '新增' : '编辑'}
          visible={showEditModal}
          footer={[
            <Button key="back" onClick={_ => setShowEditModal(false)}>
              返回
            </Button>,
            <Button key="submit" type="primary" loading={loadingEditBtn} onClick={_ => handleSubmit()}>
              确定
            </Button>
          ]}
        >
          <Input value={editForm.name} placeholder="分类名称" onChange={e => setEditForm({ name: e.target.value })} />
        </Modal>
      </div>
    </Spin>
  );
};
export default Category;

// src/views/Category.vue
<template>
  <div id="Category">
    <Card :bordered="false">
      <Button type="primary" style="margin-bottom:10px" @click="handleAdd">新增</Button>
      <Table :columns="columns" :data="dataSource"></Table>
    </Card>
    <!-- 编辑 -->
    <Modal v-model="editModal" :title="editType == ENUMEDITTYPE.ADD ? '新增' : '编辑'" footer-hide>
      <Form ref="editForm" :model="editForm">
        <FormItem prop="name" label="分类名称">
          <Input type="text" v-model="editForm.name"></Input>
        </FormItem>
        <FormItem>
          <Button type="primary" @click="handleSubmit">确定</Button>
        </FormItem>
      </Form>
    </Modal>
  </div>
</template>

<script>
import dayjs from 'dayjs';
import { Button } from 'view-design';
export default {
  data() {
    return {
      dataSource: [],
      ENUMEDITTYPE: {
        ADD: 0,
        UPDATE: 1
      },
      editType: 0,
      editModal: false,
      editForm: {
        name: ''
      },
      columns: [
        {
          type: 'index',
          align: 'center',
          width: 60
        },
        {
          title: '分类名称',
          key: 'name',
          align: 'center'
        },
        {
          title: '修改时间',
          align: 'center',
          render: (h, { row }) => <span>{dayjs(row.updatedAt).format('YYYY-MM-DD')}</span>
        },
        {
          title: '文章数',
          align: 'center',
          render: (h, { row }) => <span>{row.articles.length}</span>
        },
        {
          title: '操作',
          align: 'center',
          render: (h, { row }) => {
            return (
              <div>
                <Button type="primary" style="margin-right:7px" on-click={_ => this.handleUpdate(row)}>
                  编辑
                </Button>
                <Button type="error" on-click={_ => this.handleDelete(row)}>
                  删除
                </Button>
              </div>
            );
          }
        }
      ]
    };
  },
  created() {
    this.init();
  },
  methods: {
    async init() {
      this.getData();
    },
    async getData() {
      let res = await this.$http('/category');
      this.dataSource = res.result.data;
    },
    async handleSubmit() {
      let res = await this.$http({
        url: `/category${this.editType == this.ENUMEDITTYPE.UPDATE ? '/' + this.editForm.id : ''}`,
        method: this.editType == this.ENUMEDITTYPE.ADD ? 'post' : 'put',
        data: { ...this.editForm }
      });
      if (res.status == 'success') {
        this.$Message.success(res.message);
        this.editModal = false;
        this.getData();
      } else {
        this.$Message.error(res.message);
      }
    },
    handleAdd() {
      this.editType = this.ENUMEDITTYPE.ADD;
      this.editForm = Object.assign({}, { name: '' });
      this.editModal = true;
    },
    handleUpdate(row) {
      this.editType = this.ENUMEDITTYPE.UPDATE;
      this.editForm = Object.assign({}, row);
      this.editModal = true;
    },
    async handleDelete(row) {
      // TODO 有文章不能删
      let res = await this.$http({
        method: 'delete',
        url: `/category/${row.id}`
      });
      if (res.status == 'success') {
        this.$Message.success('删除成功');
        this.getData();
      } else {
        this.$Message.error(res.message);
      }
    }
  }
};
</script>

<style></style>
