// src/views/Writing/index.tsx
import React, { useState, useEffect } from 'react';
import { Tooltip, Upload, Modal, Button, Input, Radio, Form, Select, message, Divider, Spin } from 'antd';
import { FileImageOutlined, FullscreenOutlined, FullscreenExitOutlined } from '@ant-design/icons';
import Editor from '../../components/Editor';
import { RcFile } from 'antd/lib/upload';
import Axios, { AxiosResponse } from 'axios';
import environment from '../../environment';

import hljs from 'highlight.js';
import marked from 'marked';
import 'github-markdown-css';
import 'highlight.js/styles/github.css';

import './index.less';
import { API_STATUS } from '../../constants';

const { Option } = Select;

marked.setOptions({
  breaks: true,
  highlight: function(code: any) {
    return hljs.highlightAuto(code).value;
  }
});

type editForm = {
  title: string;
  description: string;
  thumb: string;
  content: string;
  keywords: string;
  state: number;
  category_id: string | undefined;
  tags: Array<string>;
};

const initEditForm: editForm = {
  title: '',
  description: '',
  thumb: '',
  content: '',
  keywords: '',
  state: 1,
  category_id: undefined,
  tags: []
};
const layout = {
  labelCol: { span: 5 },
  wrapperCol: { span: 16 }
};
const Writing = (props: any, ref: any) => {
  const [form] = Form.useForm();
  const [loadingPage, setLoadingPage] = useState(false);
  const [editId, setEditId] = useState<Boolean | string>(false);
  const [code, setCode] = useState('');
  const [html, setHtml] = useState('');
  const [visibleEditModal, setVisibleEditModal] = useState(false);
  const [loadingSubmit, setLoadingSubmit] = useState(false);
  const [categoryList, setCategoryList] = useState([]);
  const [tagsList, setTagsList] = useState([]);
  const [addTagName, setAddTagName] = useState('');
  const [isFull, setIsFull] = useState(false);

  useEffect(() => {
    getCategoryList();
    getTagList();
    const id = props.location.search.split('=')[1];
    if (id) {
      setEditId(id);
      setLoadingPage(true);
      (Axios.get(`/article/${id}`) as AxiosResponse['data']).then((res: any) => {
        setLoadingPage(false);
        setCode(res.result.data.code);
        setHtml(res.result.data.content);
        form.setFieldsValue({
          title: res.result.data.title,
          description: res.result.data.description,
          thumb: res.result.data.thumb,
          keywords: res.result.data.keywords,
          category_id: res.result.data.category.id,
          tags: res.result.data.tags.split(',')
        });
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function getCategoryList() {
    const res = (await Axios.get('/category')) as AxiosResponse['data'];
    setCategoryList(res.result.data);
  }
  async function getTagList() {
    const res = (await Axios.get('/tag')) as AxiosResponse['data'];
    setTagsList(res.result.data);
  }

  function handleChange(newCode: string) {
    setCode(newCode);
    setHtml(marked(newCode));
  }
  async function handleImage(file: RcFile) {
    const token = (await Axios.get('/qiniutoken')) as AxiosResponse['data'];
    const req = new FormData();
    const type = file.type.split('/')[1];
    const filename = new Date().valueOf() + '.' + type;
    req.append('file', file);
    req.append('key', filename);
    req.append('token', token.result.data);
    const res: {
      hash: string;
      key: string;
    } = await Axios.post(environment.qiniuUrl, req, {
      headers: { 'Content-Type': 'multipart/form-data' }
    });
    const str = `${code}\n![图片描述](${environment.cdnUrl}/${res.key})`;
    handleChange(str);
    return Promise.reject();
  }

  function handlePublish() {
    setVisibleEditModal(true);
  }

  async function handleSubmit(value: any) {
    console.log(value);
    setLoadingSubmit(true);

    const req = {
      title: value.title,
      description: value.description,
      thumb: '',
      keywords: value.keywords,
      state: value.state,
      category_id: value.category_id,
      tags: value.tags.join(','),
      code: code,
      content: html
    };
    if (editId) {
    }
    const res = (await Axios({
      url: editId ? `/article/${editId}` : '/article',
      method: editId ? 'put' : 'post',
      data: req
    })) as AxiosResponse['data'];

    setLoadingSubmit(false);

    if (res.status === API_STATUS.SUCCESS) {
      message.success(res.message);
      props.history.push('/article');
    } else {
      message.error(res.message);
    }
  }
  async function addTag() {
    await Axios.post('/tag', { name: addTagName });
    setAddTagName('');
    getTagList();
  }

  return (
    <Spin spinning={loadingPage}>
      <div id="writing" className={isFull ? 'fullscreen' : ''}>
        <div className="tools">
          <Upload beforeUpload={handleImage}>
            <Tooltip placement="top" title="添加图片">
              <FileImageOutlined className="tools-item" />
            </Tooltip>
          </Upload>
          {isFull ? (
            <FullscreenExitOutlined className="tools-item" onClick={_ => setIsFull(false)} />
          ) : (
            <FullscreenOutlined className="tools-item" onClick={_ => setIsFull(true)} />
          )}

          <Button
            onClick={handlePublish}
            size="small"
            type="primary"
            style={{ marginRight: '8px', position: 'absolute', right: 0 }}
          >
            发布
          </Button>
        </div>

        <div className="content">
          <div className="code">
            <Editor value={code} onChange={handleChange}></Editor>
          </div>
          <div className="show">
            <div className="markdown-body" dangerouslySetInnerHTML={{ __html: html }}></div>
          </div>
        </div>

        <Modal
          title={'发布详情'}
          visible={visibleEditModal}
          footer={[
            <Button key="back" onClick={_ => setVisibleEditModal(false)}>
              返回
            </Button>,
            <Button key="submit" type="primary" loading={loadingSubmit} onClick={_ => form.submit()}>
              确定
            </Button>
          ]}
        >
          <Form form={form} {...layout} onFinish={handleSubmit} initialValues={initEditForm}>
            <Form.Item label="标题" name="title">
              <Input placeholder="输入标题" />
            </Form.Item>
            <Form.Item label="描述" name="description">
              <Input placeholder="输入描述" />
            </Form.Item>
            <Form.Item label="关键字" name="keywords">
              <Input placeholder="关键字(英文逗号隔开)" />
            </Form.Item>
            <Form.Item name="state" label="发布状态">
              <Radio.Group>
                <Radio value={0}>草稿</Radio>
                <Radio value={1}>发布</Radio>
              </Radio.Group>
            </Form.Item>
            <Form.Item name="category_id" label="分类">
              <Select placeholder="选择分类" onChange={e => form.setFieldsValue({ category_id: e })} allowClear>
                {categoryList.map((x: any, i) => (
                  <Option value={x.id} key={i}>
                    {x.name}
                  </Option>
                ))}
              </Select>
            </Form.Item>
            <Form.Item name="tags" label="标签">
              <Select
                placeholder="选择标签"
                mode="multiple"
                style={{ width: '100%' }}
                onChange={e => form.setFieldsValue({ tags: e })}
                allowClear
                dropdownRender={menu => (
                  <div>
                    {menu}
                    <Divider style={{ margin: '4px 0' }} />
                    <div style={{ display: 'flex', flexWrap: 'nowrap', padding: 8 }}>
                      <Input
                        style={{ flex: 'auto' }}
                        value={addTagName}
                        onChange={e => setAddTagName(e.target.value)}
                      />
                      <Button style={{ marginLeft: '5px' }} onClick={addTag}>
                        添加
                      </Button>
                    </div>
                  </div>
                )}
              >
                {tagsList.map((x: any, i) => (
                  <Option value={x.id} key={i}>
                    {x.name}
                  </Option>
                ))}
              </Select>
            </Form.Item>
          </Form>
        </Modal>
      </div>
    </Spin>
  );
};

export default Writing;

// src/views/Writing.vue
<template>
  <div id="Writing">
    <div class="sider">
      <div class="left">
        <Upload :before-upload="handleUpload" action>
          <Button type="primary">添加图片</Button>
        </Upload>
      </div>
      <div class="right">
        <Button type="primary" @click="publishModal = true">发布</Button>
      </div>
    </div>
    <div class="container" ref="containerRef">
      <codemirror
        class="codemirror"
        ref="codemirror"
        :value="code"
        :options="options"
        @input="onCmCodeChange"
      ></codemirror>
      <div class="show">
        <div class="markdown-body" v-html="content"></div>
      </div>
    </div>

    <!-- 发布 -->
    <Modal v-model="publishModal" title="发布文章" footer-hide>
      <Form ref="editForm" :model="editForm">
        <FormItem prop="title" label="标题">
          <Input type="text" v-model="editForm.title"></Input>
        </FormItem>
        <FormItem prop="description" label="描述">
          <Input type="text" v-model="editForm.description"></Input>
        </FormItem>
        <FormItem prop="thumb" label="缩略图">
          <UploadImg v-model="editForm.thumb"></UploadImg>
        </FormItem>
        <FormItem prop="keywords" label="关键字">
          <Input type="text" v-model="editForm.keywords" placeholder="英文逗号隔开"></Input>
        </FormItem>
        <FormItem prop="state" label="状态">
          <RadioGroup v-model="editForm.state">
            <Radio :label="0">草稿</Radio>
            <Radio :label="1">发布</Radio>
          </RadioGroup>
        </FormItem>
        <FormItem prop="category_id" label="分类">
          <Select v-model="editForm.category_id">
            <Option v-for="(it, i) in categoryList" :value="it.id" :key="i">{{ it.name }}</Option>
          </Select>
        </FormItem>
        <FormItem prop="tags" label="标签">
          <Select
            v-model="editForm.tags"
            filterable
            multiple
            allow-create
            @on-create="handleCreateTag"
          >
            <Option v-for="(it, i) in tagList" :value="it.name" :key="i">{{ it.name }}</Option>
          </Select>
        </FormItem>
        <FormItem>
          <Button type="primary" @click="handlePublish">确定</Button>
        </FormItem>
      </Form>
    </Modal>
  </div>
</template>

<script>
import settings from '../settings';
import UploadImg from '../components/UploadImg';
// main
import { codemirror } from 'vue-codemirror';
import 'codemirror/lib/codemirror.css';

// language
import 'codemirror/mode/markdown/markdown.js';
import 'codemirror/mode/javascript/javascript';
import 'codemirror/mode/vue/vue';
import 'codemirror/mode/htmlembedded/htmlembedded';
import 'codemirror/mode/css/css';

// theme
import 'codemirror/theme/monokai.css';

// addon
import 'codemirror/addon/selection/active-line.js';

// styleSelectedText
import 'codemirror/addon/selection/mark-selection.js';
import 'codemirror/addon/search/searchcursor.js';

// highlightSelectionMatches
import 'codemirror/addon/scroll/annotatescrollbar.js';
import 'codemirror/addon/search/matchesonscrollbar.js';
import 'codemirror/addon/search/searchcursor.js';
import 'codemirror/addon/search/match-highlighter.js';

// keyMap
import 'codemirror/mode/clike/clike.js';
import 'codemirror/addon/edit/matchbrackets.js';
import 'codemirror/addon/comment/comment.js';
import 'codemirror/addon/dialog/dialog.js';
import 'codemirror/addon/dialog/dialog.css';
import 'codemirror/addon/search/searchcursor.js';
import 'codemirror/addon/search/search.js';
import 'codemirror/addon/hint/show-hint.js';
import 'codemirror/addon/hint/show-hint.css';
import 'codemirror/keymap/sublime.js';

// foldGutter
import 'codemirror/addon/fold/foldgutter.css';
import 'codemirror/addon/fold/brace-fold.js';
import 'codemirror/addon/fold/comment-fold.js';
import 'codemirror/addon/fold/foldcode.js';
import 'codemirror/addon/fold/foldgutter.js';
import 'codemirror/addon/fold/indent-fold.js';
import 'codemirror/addon/fold/markdown-fold.js';
import 'codemirror/addon/fold/xml-fold.js';

// markdown

import hljs from 'highlight.js';
import marked from 'marked';
marked.setOptions({
  breaks: true,
  highlight: function(code) {
    return hljs.highlightAuto(code).value;
  }
});

import 'github-markdown-css';
import 'highlight.js/styles/github.css';

export default {
  components: {
    codemirror,
    UploadImg
  },
  computed: {
    codemirrorRef() {
      return this.$refs.codemirror;
    }
  },
  data() {
    return {
      editType: 'add',
      code: '',
      content: '',
      markedDelay: 200,
      delayTimer: null,
      options: {
        tabSize: 4,
        styleActiveLine: true,
        lineNumbers: true,
        lineWrapping: true,
        line: true,
        mode: 'text/x-markdown',
        theme: 'monokai',
        extraKeys: { Tab: 'autocomplete' }
      },
      categoryList: [],
      tagList: [],
      publishModal: false,
      editForm: {
        title: '',
        description: '',
        thumb: '',
        content: '',
        keywords: '',
        state: 1,
        category_id: '',
        tags: []
      }
    };
  },
  created() {
    this.init();
  },
  mounted() {
    this.codemirrorRef.codemirror.setSize(this.codemirrorRef.$el.clientWidth + 'px', this.$refs.containerRef.clientHeight + 'px');
  },
  methods: {
    async init() {
      await this.getCategory();
      await this.getTags();
      if (this.$route.query.id) {
        this.editType = 'edit';
        await this.getArticleDetail();
      } else {
        this.editType = 'add';
        this.setDraft();
      }
    },
    setDraft() {
      let draft = window.localStorage.getItem('draft');
      if (draft) {
        this.code = draft;
      }
    },
    onCmCodeChange(newCode) {
      clearTimeout(this.delayTimer);
      this.delayTimer = setTimeout(() => {
        this.code = newCode;
        this.content = marked(newCode);
        // 本地化草稿
        window.localStorage.setItem('draft', newCode);
      }, this.markedDelay);
    },
    async getArticleDetail() {
      let res = await this.$http(`/article/${this.$route.query.id}`);
      this.editForm = {
        title: res.result.data.title,
        description: res.result.data.description,
        thumb: res.result.data.thumb,
        keywords: res.result.data.keywords,
        state: 1,
        category_id: res.result.data.category ? res.result.data.category.id : '',
        tags: res.result.data.tags.split(',')
      };
      this.code = res.result.data.code;
    },
    async getCategory() {
      let res = await this.$http('/category');
      this.categoryList = res.result.data;
    },
    async getTags() {
      let res = await this.$http('/tag');
      this.tagList = res.result.data;
    },
    async handleCreateTag(val) {
      let res = await this.$http({
        url: '/tag',
        method: 'post',
        data: { name: val }
      });
    },
    async handlePublish() {
      let req = {
        ...this.editForm
      };
      req.tags = req.tags.join(',');
      req.code = this.code;
      req.content = this.content;
      let res = await this.$http({
        url: this.editType == 'add' ? '/article' : `/article/${this.$route.query.id}`,
        method: this.editType == 'add' ? 'post' : 'put',
        data: req
      });
      if (res.status == 'success') {
        this.handlePublish = false;
        this.$Message.success(this.editType == 'add' ? '发布成功' : '修改成功');
        window.localStorage.setItem('draft', '');
        this.$router.push('/article');
      } else {
        this.$Message.error(res.message);
      }
    },
    async handleUpload(file) {
      let reqformData = new FormData();
      let type = file.type.split('/')[1];
      let filename = new Date().valueOf() + '.' + type;
      reqformData.append('file', file);
      reqformData.append('key', filename);

      let token = await this.getQiniuToken();
      reqformData.append('token', token);

      let res = await this.$http.post(settings.qiniuUrl, reqformData, {
        headers: { 'Content-Type': 'multipart/form-data' }
      });
      this.onCmCodeChange(`${this.code}\n![图片描述](${settings.cdnUrl}/${res.key})`);

      return false;
    },
    async getQiniuToken() {
      let res = await this.$http('/qiniutoken');
      return res.result.data;
    }
  }
};
</script>
<style lang="less" scoped>
#Writing {
  width: calc(100vw - 286px);
  height: calc(100vh - 119px);
  .sider {
    height: 50px;
    line-height: 50px;
    width: 100%;
    position: relative;
    .left {
      position: absolute;
      left: 0;
      padding: 0 10px;
    }
    .right {
      position: absolute;
      right: 0;
      padding: 0 10px;
    }
  }
  .container {
    width: 100%;
    height: calc(100vh - 119px - 50px);
    display: flex;
  }
  .codemirror {
    width: 50%;
  }
  .show {
    margin: auto;
    width: 50%;
    background-color: #fff;
    height: 100%;
  }
}
.markdown-body {
  box-sizing: border-box;
  min-width: 200px;
  max-width: 980px;
  margin: 0 auto;
  padding: 45px;
  overflow-y: scroll;
  height: 100%;
}

@media (max-width: 767px) {
  .markdown-body {
    padding: 15px;
  }
}
</style>
